### ISSUE TITLE
State of CSS で出てきた知らない機能を調べる

### ISSUE THREAD

**Issue by mryhryki** [hyiromori/portfolio#512]
## Why

https://stateofcss.com/ja-jp/ で色々知らない CSS の機能が出てきたので、どういったものか調べておきたい。

## Todo

- [x] `writing-mode: vertical-lr;`
    - [writing-mode - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/writing-mode)
- [x] margin-block-start, padding-inline-end, border-inline-start
    - [margin-block-start - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/margin-block-start)
    - [padding-inline-end - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/padding-inline-end)
- [x] content-visibility
    - [content-visibility - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/content-visibility)
    - > content-visiblity: hidden を、たとえば display: none の代わりに使用することの追加の利点は、 content-visibility で非表示にしたときにレンダリングされたコンテンツがレンダリング状態を保持することです。これは、コンテンツが再度表示される場合、他のコンテンツよりも高速にレンダリングされることを意味します。
- [x] object-view-box
     - [First Look At The CSS object-view-box Property | CSS-Tricks - CSS-Tricks](https://css-tricks.com/first-look-at-the-css-object-view-box-property/)
- [x] blur(), brightness(), contrast()
- [x] backdrop-filter
    - [backdrop-filter - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/backdrop-filter)
- [x] min-content, max-content, fit-content
    - [min-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/min-content)
    - [max-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/max-content)
    - [fit-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/fit-content)
- [x] conic-gradient()
    - [conic-gradient() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/gradient/conic-gradient)
- [ ] color()
- [x] accent-color
    - [accent-color - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/accent-color)
- [x] currentcolor
    - [CSS Tips - currentColor を使ってテキストと同じ色を指定しよう](https://zenn.dev/phi/articles/css-tips-currentcolor)
    - テキストカラー (`color`) と同じ値をセットしてくれる
- [x] color-mix()
    - [color-mix() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix)
- [x] lch(), lab(), oklch(), oklab()
    - [lch() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch)
    - 色をそれぞれの色空間で表現する
- [ ] Relative Colors
    - `background-color: hsl(from var(--color) h s calc(l * 1.2))`
- [ ] Gradient Color Spaces
    - `background-image: linear-gradient(to right in hsl, black, white);`
- [x] overscroll-behavior
    - [overscroll-behavior - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/overscroll-behavior)
- [x] touch-action
    - [touch-action - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/touch-action)
- [x] scrollbar-gutter
    - [scrollbar-gutter | CSS-Tricks - CSS-Tricks](https://css-tricks.com/almanac/properties/s/scrollbar-gutter/)
    - スクロールバーの領域について定義し、スクロールバーの表示有無での表示ズレを回避する
- [x] line-clamp
    - [-webkit-line-clamp - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-line-clamp)
    - ["line-clamp" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=line-clamp)
- [x] Variable Fonts
    - [可変フォントガイド - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)
- [ ] font-palette
- [x] sin(), cos(), tan()…
    - ["sin()" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=sin%28%29)
    - Safari 以外対応していないっぽい
- [x] CSS Nesting
    - [CSS Nesting | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/css-nesting)
    - まだWDで、全然対応してなさそう
- [x] image-set()
    - [image-set() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/image/image-set)
- [x] image()
    - [image() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/image/image)

**Comment by mryhryki** [comment]
- [x] `writing-mode: vertical-lr;`
    - [writing-mode - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/writing-mode)
- [x] margin-block-start, padding-inline-end, border-inline-start
    - [margin-block-start - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/margin-block-start)
    - [padding-inline-end - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/padding-inline-end)
- [x] content-visibility
    - [content-visibility - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/content-visibility)
    - > content-visiblity: hidden を、たとえば display: none の代わりに使用することの追加の利点は、 content-visibility で非表示にしたときにレンダリングされたコンテンツがレンダリング状態を保持することです。これは、コンテンツが再度表示される場合、他のコンテンツよりも高速にレンダリングされることを意味します。
- [x] object-view-box
     - [First Look At The CSS object-view-box Property | CSS-Tricks - CSS-Tricks](https://css-tricks.com/first-look-at-the-css-object-view-box-property/)
- [x] blur(), brightness(), contrast()
- [x] backdrop-filter
    - [backdrop-filter - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/backdrop-filter)
- [x] min-content, max-content, fit-content
    - [min-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/min-content)
    - [max-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/max-content)
    - [fit-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/fit-content)
- [x] conic-gradient()
    - [conic-gradient() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/gradient/conic-gradient)
- [ ] color()
- [x] accent-color
    - [accent-color - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/accent-color)
- [x] currentcolor
    - [CSS Tips - currentColor を使ってテキストと同じ色を指定しよう](https://zenn.dev/phi/articles/css-tips-currentcolor)
    - テキストカラー (`color`) と同じ値をセットしてくれる
- [x] color-mix()
    - [color-mix() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix)
- [x] lch(), lab(), oklch(), oklab()
    - [lch() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch)
    - 色をそれぞれの色空間で表現する
- [ ] Relative Colors
    - `background-color: hsl(from var(--color) h s calc(l * 1.2))`
- [ ] Gradient Color Spaces
    - `background-image: linear-gradient(to right in hsl, black, white);`
- [x] overscroll-behavior
    - [overscroll-behavior - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/overscroll-behavior)
- [x] touch-action
    - [touch-action - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/touch-action)
- [x] scrollbar-gutter
    - [scrollbar-gutter | CSS-Tricks - CSS-Tricks](https://css-tricks.com/almanac/properties/s/scrollbar-gutter/)
    - スクロールバーの領域について定義し、スクロールバーの表示有無での表示ズレを回避する
- [x] line-clamp
    - [-webkit-line-clamp - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-line-clamp)
    - ["line-clamp" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=line-clamp)
- [x] Variable Fonts
    - [可変フォントガイド - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)
- [ ] font-palette
- [x] sin(), cos(), tan()…
    - ["sin()" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=sin%28%29)
    - Safari 以外対応していないっぽい
- [x] CSS Nesting
    - [CSS Nesting | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/css-nesting)
    - まだWDで、全然対応してなさそう
- [x] image-set()
    - [image-set() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/image/image-set)
- [x] image()
    - [image() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/image/image)

**Comment by mryhryki** [comment]
- [x] `writing-mode: vertical-lr;`
    - [writing-mode - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/writing-mode)
- [x] margin-block-start, padding-inline-end, border-inline-start
    - [margin-block-start - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/margin-block-start)
    - [padding-inline-end - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/padding-inline-end)
- [x] content-visibility
    - [content-visibility - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/content-visibility)
    - > content-visiblity: hidden を、たとえば display: none の代わりに使用することの追加の利点は、 content-visibility で非表示にしたときにレンダリングされたコンテンツがレンダリング状態を保持することです。これは、コンテンツが再度表示される場合、他のコンテンツよりも高速にレンダリングされることを意味します。
- [x] object-view-box
     - [First Look At The CSS object-view-box Property | CSS-Tricks - CSS-Tricks](https://css-tricks.com/first-look-at-the-css-object-view-box-property/)
- [x] blur(), brightness(), contrast()
- [x] backdrop-filter
    - [backdrop-filter - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/backdrop-filter)
- [x] min-content, max-content, fit-content
    - [min-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/min-content)
    - [max-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/max-content)
    - [fit-content - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/fit-content)
- [x] conic-gradient()
    - [conic-gradient() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/gradient/conic-gradient)
- [ ] color()
- [x] accent-color
    - [accent-color - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/accent-color)
- [x] currentcolor
    - [CSS Tips - currentColor を使ってテキストと同じ色を指定しよう](https://zenn.dev/phi/articles/css-tips-currentcolor)
    - テキストカラー (`color`) と同じ値をセットしてくれる
- [x] color-mix()
    - [color-mix() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix)
- [x] lch(), lab(), oklch(), oklab()
    - [lch() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch)
    - 色をそれぞれの色空間で表現する
- [ ] Relative Colors
    - `background-color: hsl(from var(--color) h s calc(l * 1.2))`
- [ ] Gradient Color Spaces
    - `background-image: linear-gradient(to right in hsl, black, white);`
- [x] overscroll-behavior
    - [overscroll-behavior - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/overscroll-behavior)
- [x] touch-action
    - [touch-action - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/touch-action)
- [x] scrollbar-gutter
    - [scrollbar-gutter | CSS-Tricks - CSS-Tricks](https://css-tricks.com/almanac/properties/s/scrollbar-gutter/)
    - スクロールバーの領域について定義し、スクロールバーの表示有無での表示ズレを回避する
- [x] line-clamp
    - [-webkit-line-clamp - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-line-clamp)
    - ["line-clamp" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=line-clamp)
- [x] Variable Fonts
    - [可変フォントガイド - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)
- [ ] font-palette
- [x] sin(), cos(), tan()…
    - ["sin()" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=sin%28%29)
    - Safari 以外対応していないっぽい
- [x] CSS Nesting
    - [CSS Nesting | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/css-nesting)
    - まだWDで、全然対応してなさそう
- [x] image-set()
    - [image-set() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/image/image-set)
- [x] image()
    - [image() - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/image/image)
