### ISSUE TITLE
Replace or remove Invalid URLs

### ISSUE THREAD

**Issue by mryhryki** [hyiromori/portfolio#829]
- [x] 404 https://www.jiji.com/jc/article?k=2022022700301 /memo/2022-02/2022-02-25-ukraine.md#4109
- [x] 404 https://www.jiji.com/jc/article?k=2022022600557 /memo/2022-02/2022-02-25-ukraine.md#4114
- [x] 404 https://www.jiji.com/jc/article?k=2022022600209 /memo/2022-02/2022-02-25-ukraine.md#4134
- [x] 404 https://www.jiji.com/jc/article?k=2022022501232 /memo/2022-02/2022-02-25-ukraine.md#4138
- [x] 404 https://www.jiji.com/jc/article?k=2022022600036 /memo/2022-02/2022-02-25-ukraine.md#4141
- [x] 404 https://www.jiji.com/jc/article?k=2022022400777 /memo/2022-02/2022-02-25-ukraine.md#4144
- [x] 404 https://www.jiji.com/jc/article?k=2022022600384 /memo/2022-02/2022-02-25-ukraine.md#4145
- [x] 404 https://www.jiji.com/jc/article?k=2022022400548 /memo/2022-02/2022-02-25-ukraine.md#4165
- [x] 404 https://www.nhk.jp/p/nw9/ts/V94JP16WGN/blog/bl/pKzjVzogRK/bp/pgDk2BNbjv/ /memo/2022-02/2022-02-25-ukraine.md#4188

https://github.com/mryhryki/portfolio/actions/runs/4276704305/jobs/7444991349
